#!/bin/bash

docker="/usr/local/bin/docker"
b2d="/usr/local/bin/boot2docker"

if [ ! -f "$docker" ];
	then
	echo "Can't find docker executable at $docker, are you sure it's installed?"
	exit 1;
fi

if [ ! -f "$b2d" ];
	then
	echo "Can't find boot2docker executable at $b2d, are you sure it's installed?"
	exit 1;
fi

unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

mkdir -p ~/.boot2docker

if [ ! -f ~/.boot2docker/boot2docker.iso ];
	then
	cp /usr/local/share/boot2docker/boot2docker.iso ~/.boot2docker/
fi

$b2d init
$b2d up
$($b2d shellinit)

docker version

docker_ip=$(boot2docker ip)

echo "IP: $docker_ip"

PS1="[Docker $docker_ip] $PS1"
